/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package statesandcapitals;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void someLibraryMethodReturnsTrue() throws Exception{
        StatesAndCapitals sut = new StatesAndCapitals();
        sut.testStatesAndCapitals();
    }
}
